
server:
  port: 8086

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 10s
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
        
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

user-service:
  client-id: user1
  client-secret: pass1

ws-service:
  client-id: userws
  client-secret: passws

jwt:
  secret: secret1_
  expiry_in_hour: 8760